<div class="container">
	
	<h1>Créer un compte</h1>
	
	<?php echo ($this->getAdditionalInfoHtml()) ?>

    <form name="new-account" method="post" action="new_account.php">
    
	        <div class="form-group">
				<label for="email">E-Mail:</label>
				<input name="email" id="email" type="email" class="form-control" />
			</div>  
			
	        <div class="form-group">
				<label for="pseudo">Pseudonyme:</label>
				<input name="pseudo" id="pseudo" type="text" class="form-control" />
				<small class="form-text text-muted">Le pseudonyme est visible des autres utilisateur.</small>
			</div>  
			
	        <div class="form-group">
				<label for="password">Mot de passe:</label>
				<input name="password" id="password" type="password" class="form-control" />
			</div>
			
	        <div class="form-group">
				<label for="password-confimation">Confirmation du mot de pases:</label>
				<input name="password-confimation" id="password-confimation" type="password" class="form-control" />
			</div>
			
			<div class="form-check">
				<input name="conditon-ok" value="yes" id="conditon-ok" type="checkbox" class="form-check-input">
				<label class="form-check-label" for="conditon-ok">Je comprends que le site est 
				version alpha et que certaines fonctionnalités peuvent ne pas fonctionner. 
				De ce faite la responsabilité des administrateurs ou des développeurs du site 
				ne serait être engagé en cas de perte de données.</label>
			</div>
			
			<button type="submit" class="btn btn-primary">Création</button>
			
			<p>Vous avez déjà un compte? <a href="login.php">Se connected ici</a>.</p>

	</form>
	
</div>