<!doctype html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title><?php echo ($this->getTitle()) ?></title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<?php echo ($this->getHeaderAddition()) ?>
		<link rel="stylesheet" href="style/polaris.css">
		 
	</head>
	
	<body>
	
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		 	<!--
		    <a class="navbar-brand" href="#">Polaris</a>
  		    -->
	  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>
  			
     		<div class="collapse navbar-collapse" id="navbarSupportedContent">
   				<ul class="navbar-nav mr-auto">
     				<li class="nav-item">
            			<a class="nav-link" href="character_sheet.php">Fiche de personnage</a>
         			</li>
     				<li class="nav-item">
            			<a class="nav-link" href="new_career.php">Métier</a>
         			</li>
     				<li class="nav-item">
            			<a class="nav-link" href="show_comptence.php">Competences</a>
         			</li>
         		</ul>
         		
         		<?php 
         		if (isUserLogIn()) {
         		    $pseudo = getLoggedUsePseudo();
         		    if (strlen($pseudo) > 80){
         		        $pseudo = substr($pseudo,0,50)."...";
         		    }
         		    echo '<form class="form-inline my-2 my-lg-0" action="logout.php">';
         		    echo '  <span class="navbar-text mr-sm-2">Bienvenu '.$pseudo.'</span>';
         		    echo '  <button class="btn btn-outline-primary" type="submit">Déconnexion</button>';
         		    echo '</form>';
         		}
         		else {
         		    echo '<form class="form-inline my-2 my-lg-0" action="login.php">
         		             <button class="btn btn-outline-primary" type="submit">Connexion</button>
         		          </form>';
         		}
         		?>
         		
     		</div>
		</nav>
	
		<main role="main" class="container">